# Generated by Django 5.2.6 on 2025-09-25 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='add_date',
            new_name='created_at',
        ),
    ]
